FROM registry.access.redhat.com/ubi9/python-312@sha256:ebd0347a0422ad0d24db801972b4c1efa6f3352e5c2553b034e6b70e91235854
WORKDIR /opt/app-root/src

ARG DEPS_HASH=unknown
LABEL deps-hash=$DEPS_HASH

COPY pyproject.toml .
RUN pip install --no-cache-dir anthropic[vertex] kubernetes rich fastapi uvicorn[standard] websockets cryptography

USER 1001
